# Generated by Django 3.0.4 on 2020-04-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
