# Generated by Django 3.0.4 on 2020-04-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='favorite',
            new_name='pin',
        ),
    ]
